version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: databaseuser
      POSTGRES_PASSWORD: database
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
